name: Keep Streamlit Alive

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        # run: curl -fsS https://atisor73-epl-dashboard.streamlit.app/
        run: curl -A "Mozilla/5.0" -L https://atisor73-epl-dashboard.streamlit.app/