name: Keep Alive

on:
  schedule:
    - cron: '0 0 * * *'   # Runs once per day at midnight UTC
  workflow_dispatch:       # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run script
        run: python keep_alive.py


jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: curl https://atisor73-epl-dashboard.streamlit.app/