name: Empty Commit Push

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Configure Git
        run: |
          git config user.name "atisor73"
          git config user.email "rosita.fu99@gmail.com"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Keep repo active"

      - name: Push commit
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/atisor73/EPL-streamlit.git
          git push origin HEAD:main



# name: Keep Streamlit Alive

# on:
#   schedule:
#     - cron: '0 * * * *'   # every hour
#   workflow_dispatch:

# jobs:
#   ping:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: List files
#         run: ls -la

#       - name: Install requests
#         run: pip install requests

#       - name: Install deps
#         run: pip install websocket-client

#       - name: Run keep alive script
#         run: python keep-alive.py



# name: Test Workflow

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0,10,20 * * *'

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print hello
#         run: echo "Hello world"
